//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.12 at 07:10:29 ���� CST 
//

package com.siqi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for add-on complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="add-on">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vendor-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vendor-display" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name-display" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="api-level" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="revision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desc-url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uses-license" type="{http://schemas.android.com/sdk/android/addon/5}uses-license"/>
 *         &lt;element name="archives" type="{http://schemas.android.com/sdk/android/addon/5}archives"/>
 *         &lt;element name="libs" type="{http://schemas.android.com/sdk/android/addon/5}libs"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "add-on", propOrder = { "vendorId", "vendorDisplay", "nameId",
		"nameDisplay", "path", "apiLevel", "revision", "description",
		"descUrl", "usesLicense", "archives", "libs" })
public class AddOn {

	@XmlElement(name = "vendor-id", required = true)
	protected String vendorId;
	@XmlElement(name = "vendor-display", required = true)
	protected String vendorDisplay;
	@XmlElement(name = "name-id", required = true)
	protected String nameId;
	@XmlElement(name = "name-display", required = true)
	protected String nameDisplay;
	@XmlElement(required = true)
	protected String path;
	@XmlElement(name = "api-level", required = true)
	protected String apiLevel;
	@XmlElement(required = true)
	protected String revision;
	@XmlElement(required = true)
	protected String description;
	@XmlElement(name = "desc-url", required = true)
	protected String descUrl;
	@XmlElement(name = "uses-license", required = true)
	protected UsesLicense usesLicense;
	@XmlElement(required = true)
	protected Archives archives;
	@XmlElement(required = true)
	protected Libs libs;

	/**
	 * Gets the value of the vendorId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVendorId() {
		return vendorId;
	}

	/**
	 * Sets the value of the vendorId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVendorId(String value) {
		this.vendorId = value;
	}

	/**
	 * Gets the value of the vendorDisplay property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVendorDisplay() {
		return vendorDisplay;
	}

	/**
	 * Sets the value of the vendorDisplay property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVendorDisplay(String value) {
		this.vendorDisplay = value;
	}

	/**
	 * Gets the value of the nameId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameId() {
		return nameId;
	}

	/**
	 * Sets the value of the nameId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameId(String value) {
		this.nameId = value;
	}

	/**
	 * Gets the value of the nameDisplay property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNameDisplay() {
		return nameDisplay;
	}

	/**
	 * Sets the value of the nameDisplay property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNameDisplay(String value) {
		this.nameDisplay = value;
	}

	/**
	 * Gets the value of the path property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPath() {
		return path;
	}

	/**
	 * Sets the value of the path property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPath(String value) {
		this.path = value;
	}

	/**
	 * Gets the value of the apiLevel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getApiLevel() {
		return apiLevel;
	}

	/**
	 * Sets the value of the apiLevel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setApiLevel(String value) {
		this.apiLevel = value;
	}

	/**
	 * Gets the value of the revision property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRevision() {
		return revision;
	}

	/**
	 * Sets the value of the revision property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRevision(String value) {
		this.revision = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the descUrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescUrl() {
		return descUrl;
	}

	/**
	 * Sets the value of the descUrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescUrl(String value) {
		this.descUrl = value;
	}

	/**
	 * Gets the value of the usesLicense property.
	 * 
	 * @return possible object is {@link UsesLicense }
	 * 
	 */
	public UsesLicense getUsesLicense() {
		return usesLicense;
	}

	/**
	 * Sets the value of the usesLicense property.
	 * 
	 * @param value
	 *            allowed object is {@link UsesLicense }
	 * 
	 */
	public void setUsesLicense(UsesLicense value) {
		this.usesLicense = value;
	}

	/**
	 * Gets the value of the archives property.
	 * 
	 * @return possible object is {@link Archives }
	 * 
	 */
	public Archives getArchives() {
		return archives;
	}

	/**
	 * Sets the value of the archives property.
	 * 
	 * @param value
	 *            allowed object is {@link Archives }
	 * 
	 */
	public void setArchives(Archives value) {
		this.archives = value;
	}

	/**
	 * Gets the value of the libs property.
	 * 
	 * @return possible object is {@link Libs }
	 * 
	 */
	public Libs getLibs() {
		return libs;
	}

	/**
	 * Sets the value of the libs property.
	 * 
	 * @param value
	 *            allowed object is {@link Libs }
	 * 
	 */
	public void setLibs(Libs value) {
		this.libs = value;
	}

}
