//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.12 at 07:10:29 ���� CST 
//

package com.siqi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for archive complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="archive">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="checksum" type="{http://schemas.android.com/sdk/android/addon/5}checksum"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="os" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "archive", propOrder = { "size", "checksum", "url" })
public class Archive {

	protected long size;
	@XmlElement(required = true)
	protected Checksum checksum;
	@XmlElement(required = true)
	protected String url;
	@XmlAttribute
	protected String os;

	/**
	 * Gets the value of the size property.
	 * 
	 */
	public long getSize() {
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 */
	public void setSize(long value) {
		this.size = value;
	}

	/**
	 * Gets the value of the checksum property.
	 * 
	 * @return possible object is {@link Checksum }
	 * 
	 */
	public Checksum getChecksum() {
		return checksum;
	}

	/**
	 * Sets the value of the checksum property.
	 * 
	 * @param value
	 *            allowed object is {@link Checksum }
	 * 
	 */
	public void setChecksum(Checksum value) {
		this.checksum = value;
	}

	/**
	 * Gets the value of the url property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Sets the value of the url property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUrl(String value) {
		this.url = value;
	}

	/**
	 * Gets the value of the os property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOs() {
		return os;
	}

	/**
	 * Sets the value of the os property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOs(String value) {
		this.os = value;
	}

}
