//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.12 at 07:10:29 ���� CST 
//

package com.siqi.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.siqi.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.siqi.model
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link SdkAddon }
	 * 
	 */
	public SdkAddon createSdkAddon() {
		return new SdkAddon();
	}

	/**
	 * Create an instance of {@link Archive }
	 * 
	 */
	public Archive createArchive() {
		return new Archive();
	}

	/**
	 * Create an instance of {@link License }
	 * 
	 */
	public License createLicense() {
		return new License();
	}

	/**
	 * Create an instance of {@link Archives }
	 * 
	 */
	public Archives createArchives() {
		return new Archives();
	}

	/**
	 * Create an instance of {@link Checksum }
	 * 
	 */
	public Checksum createChecksum() {
		return new Checksum();
	}

	/**
	 * Create an instance of {@link Lib }
	 * 
	 */
	public Lib createLib() {
		return new Lib();
	}

	/**
	 * Create an instance of {@link AddOn }
	 * 
	 */
	public AddOn createAddOn() {
		return new AddOn();
	}

	/**
	 * Create an instance of {@link Libs }
	 * 
	 */
	public Libs createLibs() {
		return new Libs();
	}

	/**
	 * Create an instance of {@link UsesLicense }
	 * 
	 */
	public UsesLicense createUsesLicense() {
		return new UsesLicense();
	}

}
